#!/bin/bash

file=$1
title=$2

touch tmp

echo "" >> tmp
echo "#### {{current_date}} $title" >> tmp

input="$(</dev/stdin)"

echo "$input" >> tmp

sed -i 's/.*/&\\/g' tmp

text="$(cat tmp)"
sed -i "/{{feed}}/a $text" $file
rm tmp
