#!/bin/bash

file=$1
title=$2

touch tmp.txt

echo "" >> tmp.txt
echo "#### {{current_date}} $title" >> tmp.txt

input="$(</dev/stdin)"

echo "$input" >> tmp.txt

sed -i '/{{feed}}/r tmp.txt' $file
rm tmp.txt
