#!/bin/bash

# this is where the times are stored
touch ~/.proctimes

case $1 in
	-h | --help )
		printf "small utility for tracking time!
usage: proctrack [options] [program]
options:
  'focus [name]' for arbitrary activities which may not be programs. will add an entry for [name] in .proctimes
  'focus end'    ends timer started by 'focus [name]'"
	;;
	focus )
		printf "starting timer for %s" "$1"
		if [[ $# -gt 1 ]]; then case $2 in
			end )
				printf "ending timer"
			;;
			* )
				printf "sorry, not sure what you want me to do :)"
			;;
		esac fi
	;;
	* )
		# gets the new run time from proctime
		newtime=$(proctime "$1")
		# adds appropriate number of zeros (maybe not necessary?)
		numunits=$(echo "$newtime" | sed -e 's/\(.\)/\1\n/g' | grep - c":")
		numunits=$numunits+1
		case $numunits in
			2 )
				newtime="00:00:${newtime}"
			;;
			3 )
				newtime="00:${newtime}"
			;;
		esac
		prpnd "$(date +%d%m%y)	${1}	${newtime}" ~/.proctimes
	;;
esac
