#!/bin/python

import sys
from datetime import date

today = date.today()

for line in sys.stdin:
	if "{{date}}" in line:
		line = line.replace("{{date}}", today.strftime("%d%m%y"))
	
	sys.stdout.write(line)
