#!/bin/python

import os
import sys
import fnmatch
import re

def files_within(directory_path, pattern="*"):
    for dirpath, dirnames, filenames in os.walk(directory_path):
        for file_name in fnmatch.filter(filenames, pattern):
            yield os.path.join(dirpath, file_name)

for index, line in enumerate(sys.stdin):
    if "{{files}}" in line:
        html = "<ul>\n"
        for file in files_within("./docs/files"):
            # sanitized = re.search(r"([^\/.]+[.]{0,1}\w*)$", file).group()
            sanitized = file[13:]
            html += "\t<li><a href=\"" + str(file[7:]) + "\">" + sanitized + "</a></li>\n"
        html += "</ul>\n"
        line = line.replace("{{files}}", html)
    sys.stdout.write(line)
