#!/usr/bin/python

import os
import sys
import fnmatch
import re

#DOC: uses some cursed recursize walk function
def files_within(directory_path, pattern="*"):
    for dirpath, dirnames, filenames in os.walk(directory_path):
        for file_name in fnmatch.filter(filenames, pattern):
            yield os.path.join(dirpath, file_name)

for index, line in enumerate(sys.stdin):
    if "{{files}}" in line:
        html = "<ul>\n"
        # replace hardecoded path
        for file in files_within("./public/files"):
            # sanitized = re.search(r"([^\/.]+[.]{0,1}\w*)$", file).group()
            #DOC: just removes base file path
            sanitized = file[13:]
            
            #DOC: adds file name and link to list
            html += "\t<li><a href=\"" + str(file[7:]) + "\">" + sanitized + "</a></li>\n"
                
        html += "</ul>\n"
        line = line.replace("{{files}}", html)
    sys.stdout.write(line)
