#!/bin/python

import os
import sys
import glob

# os.chdir('..')
file = open(".pillar.toml").readlines()
for lines in file:
    k = lines.split()
    if len(k) > 0 and k[0] == "granite_path":
        granite_path = k[2]

for line in sys.stdin:
    if "{{latest}}" in line:
        latest = "<ul>\n"
        abspath = os.path.abspath(granite_path[1:-1])
        files = glob.glob(abspath + "/*.gn")
        files.sort(key=os.path.getmtime, reverse=True)
        for file in files:
            title = "~default~"
            page = open(file).readlines()
            for p_line in page:
                if "title:" in p_line:
                    title = p_line[7:-1]
            file = file.replace(".gn", ".html")
            latest += "\t<li><a href=\"" + file[len(abspath)+1:] + "\">" + title + "</a></li>\n"
        latest += "</ul>"
        line = line.replace("{{latest}}", latest)
    sys.stdout.write(line)
