#!/usr/bin/python

import os
import sys
import glob
import time

# DOC: gets granite path
file = open(".pillar.toml").readlines()
for lines in file:
    k = lines.split()
    if len(k) > 0 and k[0] == "granite_path":
        granite_path = k[2]
    if len(k) > 0 and k[0] == "latest_length":
        latest_length = k[2]

for index, line in enumerate(sys.stdin):
    # DOC: replaces {{latest}}
    if "{{latest}}" in line:
        latest = "<h3>Latest:</h3>\n<ul>\n"
        # DOC: sorts files in /pages by reversed edit time
        abspath = os.path.abspath(granite_path[1:-1])
        files = glob.glob(abspath + "/*.gn")
        files.sort(key=os.path.getmtime, reverse=True)

        for file in files[:int(latest_length)]:
            # DOC: finds title
            title = "~default~"
            page = open(file).readlines()
            for p_line in page:
                if "title:" in p_line:
                    title = p_line[7:-1]
                    #DOC: break once a title is found to prevent potential later matches
                    break

            # DOC: adds edit time to list
            latest += \
                "\t<li>" + \
                time.strftime("%d%m%y", time.gmtime(os.path.getmtime(file[len(abspath)-len(granite_path)+3:]))) + \
                " - <a href=\""

            file = file.replace(".gn", ".html")

            # DOC: adds file link and title to list
            latest += \
                file[len(abspath)+1:] + \
                "\">" + \
                title + \
                "</a></li>\n"

        latest += "</ul>"
        line = line.replace("{{latest}}", latest)
    sys.stdout.write(line)
