#!/usr/bin/python

import os
import sys

#DOC: gets music path
file = open(".pillar.toml").readlines()
for lines in file:
    k = lines.split()
    if len(k) > 0 and k[0] == "music_path":
        music_path = k[2]

for index, line in enumerate(sys.stdin):
    if "{{music}}" in line:
        albums = "<ul>\n"
        #DOC: gets album names and adds them to list
        for file in os.scandir(music_path[1:-1]):
            if file.is_dir():
                albums += "\t<li>" + file.path[len(music_path)-2:] + "</li>\n"
        albums += "</ul>"
        line = line.replace("{{music}}", albums)
    sys.stdout.write(line)
