#!/usr/bin/python

import os
import sys
import datetime
import glob
import time


# rss format:
# <rss xmlns:atom="http://www.w3.org/2005/Atom" version="2.0">
# 	<channel>
# 		<title>Mineral Existence</title>
# 		<description>an internet garden, tended with love and affection</description>
# 		<link>https://mineralexistence.com</link>
#
# 		<item>
# 			<title>roguelike</title>
# 			<description><p>Super work-in-progress web game. Arrow keys/wasd/hjkl to move, c to change color scheme.</p> </description>
# 			<pubDate>2019-02-21T00:00:00+00:00</pubDate>
# 			<link>https://nathanwentworth.co/projects/roguelike/</link>
# 			<guid isPermaLink="true">https://nathanwentworth.co/projects/roguelike/</guid>
# 		</item>
# 	</channel>
# </rss>


# DOC: gets granite path
def granite_path():
    file = open(".pillar.toml").readlines()
    for lines in file:
        k = lines.split()
        if len(k) > 0 and k[0] == "granite_path":
            granite_path = k[2]
        elif len(k) > 0 and k[0] == "html_path":
            html_path = k[2]
    return (granite_path, html_path)


def gen_rss():
    # DOC: base xml string
    xml = """<rss xmlns:atom="http://www.w3.org/2005/Atom" version="2.0">\n\t<channel>\n\t\t<title>Mineral Existence</title>\n\t\t<description>an internet garden, tended with love and affection</description>\n\t\t<link>https://mineralexistence.com</link>\n\t\t<language>en</language>\n"""

    xml_pages = {}

    abspath = os.path.abspath(granite_path()[0][1:-1])
    files = glob.glob(abspath + "/*.gn")
    files.sort(key=os.path.getmtime, reverse=True)

    for file in files:
        item_xml = ""
        title = "~default~"
        page = open(file).readlines()
        for p_line in page:
            if "title:" in p_line:
                title = p_line[7:-1]
        item_xml += "\t\t<item>\n"
        item_xml += "\t\t\t<title>" + title + "</title>\n"
        
        mtime = os.path.getmtime(file)
        timestamp_str = datetime.datetime.fromtimestamp(mtime).strftime('%a, %d %b %Y %X +0900')
        item_xml += "\t\t\t<pubDate>" + timestamp_str + "</pubDate>\n"
        # Fri, 20 Aug 2021 00:00:00 +0900
        
        xml_pages[file] = item_xml

    html_files = [file.replace(".gn", ".html") for file in files]
    html_files = [file.replace("pages/", "docs/") for file in html_files]

    for file in files:
        item_xml = ""
        description = "A mystery page!"
        file = file.replace(".gn", ".html")
        url = file.replace(abspath, "https://mineralexistence.com")
        file = file.replace("pages/", "docs/")
        
        page = open(file).readlines()
        for p_line in page:
            p_line = p_line.strip()
            if "<p>" in p_line:
                description = p_line[3:-4]
                break
        
        item_xml += "\t\t\t<description>\n\t\t\t\t<![CDATA[ <p>" + description + "</p> ]]>\n\t\t\t</description>\n"
        item_xml += "\t\t\t<link>" + url + "</link>\n"
        item_xml += "\t\t\t<guid isPermaLink=\"true\">" + url + "</guid>\n"
        item_xml += "\t\t</item>\n"

        file = file.replace("docs/", "pages/")
        file = file.replace(".html", ".gn")

        xml_pages[file] += item_xml


    for file, item in xml_pages.items():
        xml += str(item)

    # DOC: closes xml string
    xml += """\n\t</channel>\n</rss>"""

    # DOC: writes to xml file
    f = open("docs/feed.xml", "w")
    f.write(xml)
    f.close()


for index, line in enumerate(sys.stdin):
    if "{{rss}}" in line:
        gen_rss()
    else:
        sys.stdout.write(line)
