#!/bin/bash

unit=$1
case $unit in
	"-h" | "--help" )
		echo "Pipe in times, or type and ctrl-d when done
Define largest unit with m (minutes), h (hours), or d (days); defaults to hours"
	;;
	"" )
		unit="h"
	;;
esac

times=$(cat)

days=0
hours=0
minutes=0
seconds=0

for t in $times; do
	numunits=$(echo $t | sed -e 's/\(.\)/\1\n/g' | grep ":" | wc -l)
	numunits=$[$numunits+1]

	case $unit in
		"m" )
			t="00:00:${t}"
		;;
		"h" )
			t="00:${t}"
		;;
		* ) ;;
	esac

	IFS=':'
	read -ra parts <<< "$t"
	IFS=' '
	d=${parts[0]}
	h=${parts[1]}
	m=${parts[2]}
	s=${parts[3]}

	if [ "$h" = "" ]; then h=0; fi
	if [ "$m" = "" ]; then m=0; fi
	if [ "$s" = "" ]; then s=0; fi
	
	days=$[10#$days+10#$d]
	hours=$[10#$hours+10#$h]
	minutes=$[10#$minutes+10#$m]
	seconds=$[10#$seconds+10#$s]
done

round(){
	echo $(printf %.$2f $(echo "scale=$2;(((10^$2)*$1)+0.5)/(10^$2)" | bc))
};

# takes a time int and a break int, returns extra and new current
# example:
# spillup 100 60.0
# > 1 40
spillup(){
	extralarge=$(echo "${1} / ${2}" | bc -l)
	decsmall=$(echo "(${extralarge} % 1) * ${2}" | bc)
	# extra large units
	echo $(round $(echo "scale=0;${extralarge} - (${extralarge} % 1)" | bc) 0)
	# new small units
	echo $(round $decsmall 0);
}

if (( seconds >= 60 )); then
	{
	  read -r extra
	  read -r new
	} <<< "$( spillup ${seconds} 60.0 )"
	minutes=$[$minutes+$extra]
	second=$new
	
	# extralarge=$(echo "${seconds} / 60.0" | bc -l)
	# decsmall=$(echo "(${extralarge} % 1) * 60" | bc)
	# extralarge=$(round $(echo "scale=0;${extralarge} - (${extralarge} % 1)" | bc) 0)
	# minutes=$[$minutes+$extralarge]
	# seconds=$(round $decsmall 0);
fi
if (( minutes >= 60 )); then
	{
	  read -r extra
	  read -r new
	} <<< "$( spillup ${minutes} 60.0 )"
	hours=$[$hours+$extra]
	minutes=$new

	# extralarge=$(echo "${minutes} / 60.0" | bc -l)
	# decsmall=$(echo "(${extralarge} % 1) * 60" | bc)
	# extralarge=$(round $(echo "scale=0;${extralarge} - (${extralarge} % 1)" | bc) 0)
	# hours=$[$hours+$extralarge]
	# minutes=$(round $decsmall 0);
fi
if (( hours >= 24 )); then
	{
	  read -r extra
	  read -r new
	} <<< "$( spillup ${hours} 24.0 )"
	days=$[$days+$extra]
	hours=$new

	# extralarge=$(echo "${hours} / 60.0" | bc -l)
	# decsmall=$(echo "(${extralarge} % 1) * 60" | bc)
	# extralarge=$(round $(echo "scale=0;${extralarge} - (${extralarge} % 1)" | bc) 0)
	# days=$[$days+$extralarge]
	# hours=$(round $decsmall 0);
fi

echo "Time (d:h:m:s)"
echo "${days}:${hours}:${minutes}:${seconds}"
# echo $[$large+$extralarge]":"$newsmall
